name: Deploy Jenkins on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
      approval:
        description: 'Approve to proceed'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no

env:
  TF_WORKING_DIR: jenkins

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Initialize Terraform
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform plan -input=false -out=tfplan

    # - name: Await Approval for Apply or Destroy
    #   if: ${{ github.event_name == 'push' || github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy' }}
    #   run: echo "Please approve to proceed with ${GITHUB_EVENT.inputs.action}"

    # - name: Terraform Apply
    #   if: ${{ github.event_name == 'push' || github.event.inputs.action == 'apply' }}
    #   working-directory: ${{ env.TF_WORKING_DIR }}
    #   run: terraform apply -input=false "tfplan"

    # - name: Terraform Destroy
    #   if: ${{ github.event.inputs.action == 'destroy' }}
    #   working-directory: ${{ env.TF_WORKING_DIR }}
    #   run: terraform destroy -auto-approve

    - name: Wait for Manual Approval
      if: ${{ github.event.inputs.approval != 'yes' }}
      run: |
        echo "You must approve the deployment before proceeding."
        exit 1

    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' && github.event.inputs.approval == 'yes' }}
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform apply -input=false "tfplan"

    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' && github.event.inputs.approval == 'yes' }}
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform destroy -auto-approve