name: Deploy Jenkins on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Approval Required
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' }}
      run: |
        echo "Please approve to proceed with Apply."
        while true; do
          read -p "Type 'yes' to approve: " input
          if [[ $input == "yes" ]]; then
            break
          fi
        done

    - name: Terraform Apply
      if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply') }}
      run: terraform apply -input=false "tfplan"

    - name: Approval Required for Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: |
        echo "Please approve to proceed with Destroy."
        while true; do
          read -p "Type 'yes' to approve: " input
          if [[ $input == "yes" ]]; then
            break
          fi
        done

    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy
