name: Terraform Destroy

on:
  workflow_dispatch:

env:
  S3_BUCKET: github-actions-terraform-plan  # Replace with your S3 bucket name
  PLAN_FILE: "tfplan"

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Download Plan from S3
      run: |
        aws s3 cp s3://${{ env.S3_BUCKET }}/terraform/${{ env.PLAN_FILE }} jenkins/${{ env.PLAN_FILE }}

    - name: Initialize Terraform
      run: |
        cd jenkins
        terraform init

    - name: Terraform Destroy
      run: |
        cd jenkins
        terraform destroy -input=false "${{ env.PLAN_FILE }}"
