name: Terraform plan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  S3_BUCKET: github-actions-terraform-plan  # Replace with your S3 bucket name
  PLAN_FILE: "tfplan"
jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Initialize Terraform
      run: |
        cd jenkins
        terraform fmt
        terraform init

    - name: Terraform Plan
      run: |
        cd jenkins
        terraform plan -input=false -out=${{ env.PLAN_FILE }}

    - name: Upload Plan to S3
      run: |
        aws s3 cp jenkins/${{ env.PLAN_FILE }} s3://${{ env.S3_BUCKET }}/terraform/${{ env.PLAN_FILE }}
      
    
