name: Terraform Apply

# on:
#   workflow_dispatch:

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Download Plan Artifact
      uses: actions/download-artifact@v3
      with:
        name: tfplan
        path: jenkins

    - name: Initialize Terraform
      run: |
        cd jenkins
        terraform fmt
        terraform init

    - name: Terraform Apply
      run: |
        cd jenkins
        terraform apply -input=false "tfplan"
